### ISSUE TITLE
How to normalize the DMS_score

### ISSUE THREAD

**Issue by jxzly** [OATML-Markslab/ProteinGym#12]
I noticed that there are some assays with very large labels, so I am wondering how to normalize the DMS_score.
Thanks.

![image](https://github.com/OATML-Markslab/ProteinGym/assets/40078806/3a04168f-6323-4342-a8b9-bb71de5fe490)

**Comment by pascalnotin** [comment]
Dear Jixian,
Assuming your question is within the context of _supervised_ training on ProteinGym DMS assays, we typically standard scale DMS_score when training the various supervised baselines reported. In the zero-shot setting, all performance metrics are unaffected by scale. 
Best,
Pascal

**Comment by BarKetPlace** [comment]
Dear Pascal,  following up on the previous question: 
- Since the range of the DMS_score varies across experiments, how is the cutoff defined for DMS_score_bin ?

Thanks, great work with the repo !

Antoine

**Comment by pascalnotin** [comment]
Dear Antoine,
Thank you! We manually examine the DMS scores distribution and if it is nicely bi-modal we select the natural cutoff point as the threshold, otherwise we set it to the median value. The [reference file](https://github.com/OATML-Markslab/ProteinGym/blob/main/reference_files/DMS_substitutions.csv) specifies which approach is used in the DMS_binarization_method field.
Best,
Pascal

**Comment by pascalnotin** [comment]
Dear Jixian,
I'm closing this issue as I believe the above addressed it. Please feel free to re-open if you have any further questions on this.
Best,
Pascal
