### ISSUE TITLE
fold_rand_multiples CV split has overlapping folds in some datasets

### ISSUE THREAD

**Issue by timt51** [OATML-Markslab/ProteinGym#13]
For example, the sequence `EVPFKVVAQFPYKSDYEDDLNFEKDQEIIVTSVEDAEVYFGEYQDSNGDVIEGIFPKSFVAVQG` from `BBC1_YEAST_Rocklin_2023_1TG0` occurs in two folds:

```
>>> df=pd.read_csv("proteingym_cv_folds_multiples_substitutions/BBC1_YEAST_Rocklin_2023_1TG0.csv")
>>> df[df["mutated_sequence"] == "EVPFKVVAQFPYKSDYEDDLNFEKDQEIIVTSVEDAEVYFGEYQDSNGDVIEGIFPKSFVAVQG"].drop(columns="mutated_sequence")
         mutant  DMS_score  DMS_score_bin  mutation_depth  fold_rand_multiples
813   F10F:W38V  -1.400813              0               2                    3
1737       W38V  -1.623593              0               1                    4
```

In the corresponding dataset, I believe this sequence only shows up once and the corresponding `DMS_score` is the average `DMS_score`.

**Comment by pascalnotin** [comment]
Hi @timt51 -- I just uploaded a new set of CV folds splits which should address the above issue. Thanks again for flagging!

**Comment by timt51** [comment]
Thank you!

**Comment by florisvdf** [comment]
@pascalnotin Since these new CV fold splits affect the model scores, does that mean that the leaderboard has been updated with new scores? Or does the leaderboard still correspond to the old CV fold splits?

**Comment by pascalnotin** [comment]
Hi @florisvdf - the above error primarily impacts the CV scheme with multiples mutants only (for newly added assays). The supervised benchmarks in ProteinGym are for single mutants only, and the CV fold splits for these have not changed.

There is a second order effect though that I will mention here for transparency, although I don't think it will change results in any meaningful way: when dealing with new assays with the above issue, ie. with multiple mutants where one of the mutant is in fact a silent mutation, we remove the silent mutation and average the scores at the "mutated_sequence" level. There are a few cases across these assays, where that effectively changes the DMS_score for single mutants (ie., scores for A1A:C2D and C2D would be averaged together as they are the same protein sequence since A1A is silent). We will eventually re-run all baselines for the assays that are impacted for consistency, but that will likely have no effect on top level results.

**Comment by florisvdf** [comment]
@pascalnotin Ok that makes sense, thanks for clarifying!
