### ISSUE TITLE
Structure mismatch with mutated sequence.

### ISSUE THREAD

**Issue by LTEnjoy** [OATML-Markslab/ProteinGym#18]
Hi, thank you for your great effort to build such complete benchmark!

I an confused that for some datasets with long wild type sequences, the structures you provided don't have the same length with the mutated sequences, which means some structure-based baselines couldn't work correctly (they assmue the structure and sequence should have the same length).  As an example, the length of the sequence in dataset "A0A140D2T1_ZIKV_Sourisseau_2019" is 3423, but the "A0A140D2T1_ZIKV.pdb" only offers 3D coordinates of 504 residues. I wonder how did you address this problem?

Thank you in advance and looking forward to your reply!

**Comment by pascalnotin** [comment]
Dear Jin,

Thank you! We provide AF2-predicted structures of full sequences for all DMS assays in ProteinGym except for 3 proteins: 
- A0A140D2T1_ZIKV 
- POLG_HCVJF
- BRCA2_HUMAN
Structure prediction with AF2 for these 3 proteins kept failing due to their size (they are the 3 longest proteins in ProteinGym, with length over 3k residues). 

For the first two proteins (A0A140D2T1_ZIKV and POLG_HCVJF), the mutated range in the assay is localized on a smaller region of the protein (respectively residues 291-794 and 1994-2079 -- see the region_mutated field in the [DMS reference file](https://github.com/OATML-Markslab/ProteinGym/blob/main/reference_files/DMS_substitutions.csv)). So we generated structures for these two subregions of the protein. 

For the third protein (BRCA2_HUMAN), the mutated region is still relatively broad (388-2654), so we instead split the protein in 3 separate chunks and provided structures for each chunk.

Thank you for your question. We will include these details in the paper.

Best regards,
Pascal

**Comment by LTEnjoy** [comment]
Dear Notin, 

Thank you for your quick response! I understand the memory limitation for predicting structures of long proteins. I wonder how you use these split structures to perform zero-shot prediction for those structure-based models? 

For A0A140D2T1_ZIKV, as the structure only covers coordinates from residues 291 to 794 and 1994 to 2079, how should I formalize the input for models such as MIF-ST? Should I input the whole sequence or the subregions to predict mutation respectively?

Looking forward to your reply!

Best regards,
Jin

**Comment by pascalnotin** [comment]
Dear Jin,

Inputting the full sequence would throw an error as the sequence and structure passed to the `calc_fitness` must strictly match. I have pushed a slightly revised version of the code that details how to handle the few edge cases described in my earlier message. See in particular [these lines](https://github.com/OATML-Markslab/ProteinGym/blob/main/proteingym/baselines/carp_mif/compute_fitness.py#L148-L159).
I also included two example scripts for [CARP](https://github.com/OATML-Markslab/ProteinGym/blob/main/scripts/scoring_DMS_zero_shot/scoring_CARP_substitutions.sh) and [MIF / MIFST](https://github.com/OATML-Markslab/ProteinGym/blob/main/scripts/scoring_DMS_zero_shot/scoring_MIF_substitutions.sh) for reference.

Please let me know if any further questions on the above.

Kind regards,
Pascal

**Comment by LTEnjoy** [comment]
Thank you so much for resolving my question! I will take a look!

**Comment by LTEnjoy** [comment]
Dear Pascal,

Thank you for providing examples for reference to deal with the problem structure mismatch.

When I checked the [example code](https://github.com/OATML-Markslab/ProteinGym/blob/main/proteingym/baselines/carp_mif/compute_fitness.py#L148-L159) I found that there may be an error in this line:

``filtered_DMS_data = DMS_data[(DMS_data["mutated_position"] >= pdb_range[0]) & (DMS_data["mutated_position"] <= pdb_range[1])]``

when the mutation includes multiple sites.

Could you please provide a revised version so I can apply my model to it?

Best regards,
Jin

**Comment by pascalnotin** [comment]
Dear Jin - good catch! I just pushed a fix that should resolve that issue. Let me know if that works.
Best,
Pascal

**Comment by LTEnjoy** [comment]
Thanks! It works fine now.
