### ISSUE TITLE
Fitness Directionality in Raw DMS Files

### ISSUE THREAD

**Issue by brucejwittmann** [OATML-Markslab/ProteinGym#2]
First off, thanks for putting this collection of datasets together! It has been extremely helpful.

I wanted to clarify the expected direction of the relationship between phenotype and fitness in the [raw DMS files](https://github.com/OATML-Markslab/ProteinGym/blob/main/reference_files_description.md#raw-dms-assays-files). For DMS studies that originally had a negative correlation between phenotype and fitness (i.e. a "-1" in the "raw_DMS_directionality" column of the [ProteinGym reference files](https://github.com/OATML-Markslab/ProteinGym/blob/main/reference_files_description.md#proteingym-reference-files)), has the phenotype been adjusted in the raw files to make the relationship positive? I believe this is the case, as higher values in the "DMS_score" columns correlate with higher values in the "DMS_score_bin" column, but the [section giving raw file download instructions](https://github.com/OATML-Markslab/ProteinGym/blob/main/reference_files_description.md#raw-dms-assays-files) states that the files download are "the raw, unprocessed DMS files...". Some clarification would be greatly appreciated!

**Comment by pascalnotin** [comment]
Dear Bruce,

Thank you for the kind words - means a lot coming from you!

We adjusted the directionality in the processed files (e.g., https://marks.hms.harvard.edu/proteingym/ProteinGym_substitutions.zip) so that in these files higher values of the DMS_score should always correlate with higher fitness (and also higher values of the DMS_score_bin column). The raw files (e.g., https://marks.hms.harvard.edu/proteingym/raw/substitutions_raw_DMS.zip) should in principle not have this correction.

Kind regards,
Pascal

**Comment by brucejwittmann** [comment]
Thanks, Pascal! That clears things up for me :)
