### ISSUE TITLE
How to split "includes_multiple_mutants" dataset by contiguous scheme or modulo operator?

### ISSUE THREAD

**Issue by jxzly** [OATML-Markslab/ProteinGym#6]
I am wondering that how to split "includes_multiple_mutants" dataset by contiguous scheme or modulo operator?
May you share your split files?

**Comment by pascalnotin** [comment]
Hi @jxzly - I just updated the README with [links to the various CV schemes available](https://github.com/OATML-Markslab/ProteinGym/blob/main/README.md?plain=1#L98-L100). Note that the contiguous and modulo cross validation schemes were developed only for single mutants, since the assignment of multiple mutants to separate contiguous/modulo folds is in most cases not possible.

**Comment by jxzly** [comment]
Thanks.  But why can I found the contiguous and modulo cross validation score of multiple mutants  in https://marks.hms.harvard.edu/proteingym/DMS_supervised_substitutions_scores.csv.

**Comment by pascalnotin** [comment]
Please refer to the CV schemes files I linked up above. In particular, these scores were obtained by training on filtered versions of these assays where all multiple mutants were removed (and all singles were assigned to a fold as per the procedure described in the paper).

**Comment by pascalnotin** [comment]
Dear Jixian,
Closing this issue as I believe the above addressed your initial question. Feel free to re-open it if you have any further queries related to this topic.
Kind regards,
Pascal
